[workspace]
resolver = "2"
members = [
    "wasmesh-pod",
    "wasm-service",
    "wasmesh-ctl",
]
exclude = [
    "wasmesh-abi",
    "wasmesh-vm",
    "wasmesh-macros",
    "examples/simple",
    "examples/vm",
]
