[workspace]
resolver = "2"
members = [
    "pod",
    "service/rust/wasmesh-macros",
    "service/rust/wasmesh",
    "service/rust/examples/simple",
]
exclude = [
    "ctl",
    "wasmesh-abi",
    "wasmesh-vm",
]
