[alias]
run-simple = "run -- serve 127.0.0.1:9090 examples/simple/target/wasm32-wasi/debug/simple.wasm -- -k=v x"
run-simple-release = "run --release -- serve 127.0.0.1:9090 examples/simple/target/wasm32-wasi/release/simple.wasm -- -k=v x"
run-simple-release-llvm = "run --release --features=llvm -- serve 127.0.0.1:9090 examples/simple/target/wasm32-wasi/release/simple.wasm -- -k=v x"
