[alias]
build-pod = "build --bin=wasmesh-pod"
build-simple = "build --target=wasm32-wasi --package=simple --target-dir=service/rust/examples/target"
run-simple = "run -- serve --threads=16 --http=127.0.0.1:9090 --rpc=127.0.0.1:9091 service/rust/examples/target/wasm32-wasi/debug/simple.wasm -- -k=v x"
run-simple-release = "run --release -- serve --threads=16 --http=127.0.0.1:9090 --rpc=127.0.0.1:9091 service/rust/examples/target/wasm32-wasi/release/simple.wasm -- -k=v x"
run-simple-release-llvm = "run --release --no-default-features --features=llvm -- serve --threads=16 --http=127.0.0.1:9090 --rpc=127.0.0.1:9091 service/rust/examples/target/wasm32-wasi/release/simple.wasm -- -k=v x"
